/* 
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Category
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CategoryTests
    {
        // TODO uncomment below to declare an instance variable for Category
        //private Category instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Category
            //instance = new Category();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Category
        /// </summary>
        [Test]
        public void CategoryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Category
            //Assert.IsInstanceOf(typeof(Category), instance);
        }


        /// <summary>
        /// Test the property 'CategoryID'
        /// </summary>
        [Test]
        public void CategoryIDTest()
        {
            // TODO unit test for the property 'CategoryID'
        }
        /// <summary>
        /// Test the property 'CategoryName'
        /// </summary>
        [Test]
        public void CategoryNameTest()
        {
            // TODO unit test for the property 'CategoryName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Picture'
        /// </summary>
        [Test]
        public void PictureTest()
        {
            // TODO unit test for the property 'Picture'
        }

    }

}
