/* 
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ProductResource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductResourceTests
    {
        // TODO uncomment below to declare an instance variable for ProductResource
        //private ProductResource instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProductResource
            //instance = new ProductResource();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProductResource
        /// </summary>
        [Test]
        public void ProductResourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ProductResource
            //Assert.IsInstanceOf(typeof(ProductResource), instance);
        }


        /// <summary>
        /// Test the property 'ProductID'
        /// </summary>
        [Test]
        public void ProductIDTest()
        {
            // TODO unit test for the property 'ProductID'
        }
        /// <summary>
        /// Test the property 'ProductName'
        /// </summary>
        [Test]
        public void ProductNameTest()
        {
            // TODO unit test for the property 'ProductName'
        }
        /// <summary>
        /// Test the property 'QuantityPerUnit'
        /// </summary>
        [Test]
        public void QuantityPerUnitTest()
        {
            // TODO unit test for the property 'QuantityPerUnit'
        }
        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [Test]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }
        /// <summary>
        /// Test the property 'UnitsInStock'
        /// </summary>
        [Test]
        public void UnitsInStockTest()
        {
            // TODO unit test for the property 'UnitsInStock'
        }
        /// <summary>
        /// Test the property 'UnitsOnOrder'
        /// </summary>
        [Test]
        public void UnitsOnOrderTest()
        {
            // TODO unit test for the property 'UnitsOnOrder'
        }
        /// <summary>
        /// Test the property 'ReorderLevel'
        /// </summary>
        [Test]
        public void ReorderLevelTest()
        {
            // TODO unit test for the property 'ReorderLevel'
        }
        /// <summary>
        /// Test the property 'Discontinued'
        /// </summary>
        [Test]
        public void DiscontinuedTest()
        {
            // TODO unit test for the property 'Discontinued'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'Supplier'
        /// </summary>
        [Test]
        public void SupplierTest()
        {
            // TODO unit test for the property 'Supplier'
        }

    }

}
