/* 
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CategoryApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CategoryApiTests
    {
        private CategoryApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CategoryApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CategoryApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' CategoryApi
            //Assert.IsInstanceOf(typeof(CategoryApi), instance);
        }

        
        /// <summary>
        /// Test ApiCategoryGet
        /// </summary>
        [Test]
        public void ApiCategoryGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiCategoryGet();
            //Assert.IsInstanceOf(typeof(List<Category>), response, "response is List<Category>");
        }
        
        /// <summary>
        /// Test ApiCategoryImageIdGet
        /// </summary>
        [Test]
        public void ApiCategoryImageIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.ApiCategoryImageIdGet(id);
            //Assert.IsInstanceOf(typeof(byte[]), response, "response is byte[]");
        }
        
        /// <summary>
        /// Test ApiCategoryImageIdPut
        /// </summary>
        [Test]
        public void ApiCategoryImageIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //System.IO.Stream uploadedFile = null;
            //instance.ApiCategoryImageIdPut(id, uploadedFile);
            
        }
        
    }

}
